name: Build & Test

on:
  pull_request:
    paths:
      - '.github/workflows/ci.yml'
      - 'src/**'
      - 'vendor/**'
      - 'tests/**'
      - '*.js'

jobs:
  build-and-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node-version: [ 16.x, 18.x, 20.x ]
        os: [ ubuntu-latest, macos-latest, windows-latest, linux-arm ]
      fail-fast: false
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: Add msbuild to PATH
        if: matrix.os == 'windows-latest'
        uses: microsoft/setup-msbuild@v2
      - name: Build
        run: |
          npm install && npm run rebuild
      - name: Test
        uses: nick-fields/retry@v3
        with:
          max_attempts: 3
          retry_on: error
          timeout_minutes: 6
          command: |
            npm test

  build-and-test-alpine:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 16, 18, 20 ]
    container: node:${{ matrix.node-version }}-alpine
    steps:
      - uses: actions/checkout@v4
      - name: install build deps
        run: |
          apk add g++ make python3
      - name: Build
        run: |
          npm install && npm run rebuild
      - name: Test
        run: |
          npm test
        timeout-minutes: 4
